---
jaffle_shop:
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: postgres
      password: Rahul@1234
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
  target: dev
