dhwani_dbt:
  target: dev
  outputs:
    dev:
      dbname: dhwani_db
      host: host.docker.internal
      password: Rahul@1234
      port: 5432
      schema: prod
      type: postgres
      user: postgres
